name: Test
on: [push, pull_request]

jobs:
  test:
    name: Go ${{ matrix.go }} Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        go:
          - "stable"
          - "1.26"
          - "1.25"
          - "1.24"

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: |
          make test
          make test-xrayaws
          make test-xrayaws-v2
        shell: bash

      - name: Send coverage
        uses: shogo82148/actions-goveralls@9606dbc5ac5cf888a0e9ef901515c3cd516a2790 # v1.11.0
        with:
          path-to-profile: profile.cov
          flag-name: OS-${{ matrix.os }}-Go-${{ matrix.go }}
          parallel: true
      - name: Send coverage of xrayaws
        uses: shogo82148/actions-goveralls@9606dbc5ac5cf888a0e9ef901515c3cd516a2790 # v1.11.0
        with:
          path-to-profile: profile.cov
          flag-name: OS-${{ matrix.os }}-Go-${{ matrix.go }}-xrayaws-v1
          working-directory: xrayaws
          parallel: true

  # notifies that all test jobs are finished.
  finish:
    needs:
      - test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@9606dbc5ac5cf888a0e9ef901515c3cd516a2790 # v1.11.0
        with:
          parallel-finished: true
