name: Test
on: [push, pull_request]

jobs:
  test:
    name: Go ${{ matrix.go }} Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        go:
          - "stable"
          - "1.23"
          - "1.22"
          - "1.21"

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: |
          make test
          make test-xrayaws
          make test-xrayaws-v2
        shell: bash

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          flag-name: OS-${{ matrix.os }}-Go-${{ matrix.go }}
          parallel: true
      - name: Send coverage of xrayaws
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          flag-name: OS-${{ matrix.os }}-Go-${{ matrix.go }}-xrayaws-v1
          working-directory: xrayaws
          parallel: true

  # notifies that all test jobs are finished.
  finish:
    needs:
      - test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
