name: Test
on: [push, pull_request]

env:
  GO111MODULE: "on"

jobs:

  test:
    name: Go ${{ matrix.go }} Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        go:
          - '1.13'
          - '1.14'
          - '1'

    steps:

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: go mod download
        shell: bash

      # Take care of Multi-Module Repositories
      # ref. https://github.com/golang/go/wiki/Modules#faqs--multi-module-repositories
      - name: "Take care of Multi-Module Repositories: xrayaws"
        shell: bash
        working-directory: xrayaws
        run: |
          DEP_XRAYAWS=$(shell cat go.mod | grep -v module | grep github.com/shogo82148/aws-xray-yasdk-go | cut -d' ' -f2)
          go mod edit -replace github.com/shogo82148/aws-xray-yasdk-go@${DEP_XRAYAWS}=../
      - name: "Take care of Multi-Module Repositories: xrayaws-v2"
        shell: bash
        working-directory: xrayaws-v2
        run: |
          DEP_XRAYAWS=$(shell cat go.mod | grep -v module | grep github.com/shogo82148/aws-xray-yasdk-go | cut -d' ' -f2)
          go mod edit -replace github.com/shogo82148/aws-xray-yasdk-go@${DEP_XRAYAWS}=../

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          flag-name: OS-${{ matrix.os }}-Go-${{ matrix.go }}
          parallel: true

  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
