name: Test
on: [push, pull_request]

env:
  GO111MODULE: "on"

jobs:
  test:
    name: Go ${{ matrix.go }} Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        go:
          - "stable"
          - "1.21.0-rc.4"
          - "1.20"
          - "1.19"
          - "1.18"
          - "1.17"
          - "1.16"
        goexperiment: [""]
        include:
          # test with GOEXPERIMENT=loopvar
          # https://github.com/golang/go/wiki/LoopvarExperiment
          - go: "1.21.0-rc.4"
            os: ubuntu-latest
            goexperiment: "loopvar"

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Test
        run: |
          make test
          make test-xrayaws
          make test-xrayaws-v2
        shell: bash
        env:
          GOEXPERIMENT: ${{ matrix.goexperiment }}

      - name: Send coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          flag-name: OS-${{ matrix.os }}-Go-${{ matrix.go }}
          parallel: true
      - name: Send coverage of xrayaws
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
          flag-name: OS-${{ matrix.os }}-Go-${{ matrix.go }}-xrayaws-v1
          working-directory: xrayaws
          parallel: true

  # notifies that all test jobs are finished.
  finish:
    needs:
      - test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
