name: update
on:
  schedule:
    - cron: "24 15 * * *"
  workflow_dispatch:

jobs:
  update:
    name: update AWSWhitelist.json
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable

      - name: update for AWS SDK v1
        run: |
          ./update-whitelist.sh
          go generate ./...
        working-directory: ./xrayaws

      - name: update for AWS SDK v2
        run: |
          ./update-whitelist.sh
          go generate ./...
        working-directory: ./xrayaws-v2

      - uses: shogo82148/actions-commit-and-create-pr@b1322fe9da4037e9720e34ea221997cffcd3498d # v1.1.4
